#!/bin/bash
###########################################################
#
# Copyright (C) 2010 Anders Håål, Ingenjorsbyn AB
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#
# 
# 
###########################################################



trap 'aborted' INT KILL HUP

PATH=/sbin:/usr/sbin:$PATH

function getinstalldir() {
  curdir=`pwd`
  installpath=`dirname $1`
  # Check if the path is absolut or relative
  echo $installpath | grep "^/" > /dev/null

  if [ $? -eq 0 ] ; then
    insdir=$installpath
  else
    insdir=$curdir/$installpath
  fi
  echo $insdir
}

function setifsnewline {
  CURIFS=$IFS
  IFS='
'
}

function unsetifs {
  IFS=$CURIFS
}

function postinstall () {
  postcount=`expr $postcount + 1`
  echo -e "$postcount) $1" >> $POST_INSTALL
}

function beginnew () {
  echo $1
}

function begin () {
  echo -n $1
}

function end () {
  echo  ".... Done " $1
}

function getout {
  echo "Fix your installation errors and re-run $0"
  #cleanup
  exit
}

function errormsg () {
  echo $1 "... Error"
}

function warnmsg () {
  echo " $1" "... Warning"
}

function progress () {
  echo $1 "... OK"
}

function headline() {
  echo
  echo -en "\\033[1;34m"
  echo $@
  str=`echo $@ |  sed -e "s/ /_/g"`
  len=`expr length $str `  
  while [ $len -ne 0 ]
  do 
    echo -n = 
    len=`expr $len - 1 ` 
  done
  echo -en "\\033[0;39m"
  echo
}

function getdate() {
  date +'%Y%m%d%H%M'
}

function checkpackage() {
  rpm -q $1 >/dev/null
  if [ $? -ne 0 ] ; then
    echo "Package $1 is missing - exiting"
    exit 1
  fi 
}

function usage {
  echo "Usage: $0: -U user -I directory -J java_home "
  echo "-u show usage"
  echo "-U the user name to install BISDWcheck as and run the daemon as - default nagios"
  echo "-J java home directory - default is none"
  echo "-I installation directory for bisdw - default /opt/socbox/addons/bisdw"
  echo "-R unistall - permanently remove the installation" 
  echo "-X upgrade from current version - if possible"
}


scriptname=`basename $0`
tempdir=`mktemp -d`

#
# Setup environment
#


#
# Read command line options
#
# Default - do nothing
#

USERINIT=nagios
NAGIOSHOST=localhost
BISDW="/opt/socbox/addons/bisdw"
JAVA_HOME=""
unistall=false
upgrade=false

VERSION=$(basename `pwd` | sed -e "s/^.*-//")


echo "Welcome to bisdw $VERSION installer"
echo "===================================="
echo "Copyright Anders Håål, Ingenjörsbyn AB 2011"
echo "Licensed under GPL version 2"

while getopts U:I:J:uR:X name
do
  case $name in
    U)  USERINIT="$OPTARG";;
    I)  BISDW="$OPTARG";;
    J)  JAVA_HOME="$OPTARG";;
    X)  upgrade=true;;
    R)  uninstall=true;;
    u)  usage; exit 0;;
  esac
done

shift $(($OPTIND - 1))

if [ "x$uninstall" = "xtrue" ] ; then
  echo uninstall
  exit 0
fi

headline "Pre-installation verification"

echo "Checking software dependencies"

if [ "x$upgrade" = "xtrue" ] ; then
  checkpackage sqlite
  checkpackage javasqlite
fi

echo "All software installed"


id $USERINIT > /dev/null 2>&1
if [ $? -ne 0 ] ; then
  errormsg "User $USERINIT do not exists"
  initerror=true
else 
  echo User "$USERINIT exists"
fi

if [ "$upgrade" = "false" ] ; then
  if [ -d $BISDW ] ; then
    errormsg "Directory $BISDW already exists"
    initerror=true
  else 
    echo "Directory $BISDW do not exists, will be created"
  fi
fi

if [ "x$JAVA_HOME" = "x" ] ; then
  which java > /dev/null 2>&1
  if [ $? != 0 ] ; then
    errormsg "Java do not exists in path $PATH"
    initerror=true
  fi
elif [ ! -f $JAVA_HOME/bin/java ] ; then
  errormsg "Java do not exists in $JAVA_HOME/bin"
  initerror=true
else 
  echo "Java runtime exists"
fi
  

if [ "$upgrade" = "true" ] ; then

  #Check if the current version can be upgraded
  oldversion=$(head -1 $BISDW/version.txt)
  newversion=$(basename `pwd` | cut -d"-" -f2)
  
  upgradedir=${BISDW}_$oldversion  
  if [ -d $upgradedir ] ; then
    errormsg "Copy directory $upgradedir exists, must be removed to upgrade bisdw"
    initerror=true
  fi

    
  migline=$(grep $oldversion:$newversion: migrationpath.txt 2>&1)
  migoldver=$(echo $migline | cut -d":" -f1)
  mignewver=$(echo $migline | cut -d":" -f2)

  

  if [ "x$migoldver" = "x$oldversion" -a "x$mignewver" = "x$newversion" ] ; then
    echo "Upgrading bisdw from $oldversion to $newversion"
  else
    errormsg "Upgrading bisdw from $oldversion to $newversion is not supported"
    initerror=true
  fi
  migscript=$(echo $migline | cut -d":" -f3)
fi

if [ "$initerror" = "true" ] ; then
  getout
else 
  echo "Pre-installation completed successful"
fi



# Create a backup directory of old bisdw installation
if [ "$upgrade" = "true" ] ; then
  service bisdwd stop
  echo "Moving old installation to $upgradedir"
  mv $BISDW $upgradedir 
fi


headline "Do installation of bisdw $newversion"
if [ ! -d $BISDW ] ; then
    echo "Create installation directory $BISDW"
    mkdir -p $BISDW
    mkdir $BISDW/bin
    mkdir $BISDW/customlib
    mkdir $BISDW/etc
  
    echo "Copy files to installation directory"
    cp -a lib $BISDW
    cp -a resources $BISDW
    cp -a etc $BISDW
    
    echo $VERSION > $BISDW/version.txt
    
    echo "Parse all script files"
    # Parse all shell scripts
    for i in `ls scripts/*.template` ; do
      cat  $i| sed -e "s#%BISDW%#$BISDW#g" \
        -e "s#%VERSION%#$VERSION#g" \
        -e "s#%USERINIT%#$USERINIT#g" \
        -e "s#%JAVA_HOME%#$JAVA_HOME#g" > $BISDW/bin/`basename ${i%\.template}`
    done
    chmod 750 $BISDW/bin/* 

    echo "Install init.d script bisdwd in /etc/init.d"
    cp $BISDW/bin/bisdwd /etc/init.d
    chmod 755 /etc/init.d/bisdwd
    chkconfig --add bisdwd
    
    echo "Change ownership and permissions to install user $USERINIT"
    chown -R $USERINIT:`id -gn $USERINIT` $BISDW
    echo "Installations complete"
else
   errormsg "Directory $BISDW already exists"
   initerror=true
   getout
fi

if [ "$upgrade" = "true" ] ; then
  headline "Upgrade of bisdw $newversion with $oldversion"
  echo "Copy customlib jars"
  cp -a $upgradedir/customlib/* $BISDW/customlib/
  echo "Running migrations scripts"    
  sh ./migscripts/$migscript $BISDW $upgradedir
fi

if [ ! -d $BISDW ] ; then
  echo "Set permission of the installation"
  chmod -R o-rwx $BISDW/etc
fi